Repository sparta-nbcamp-ch3-advanced-team5/Look-out-the-window, pull requests merged in 2025-05, with the labels that each got.

#16 Feat/#14
  Look-out-the-window/Look-out-the-window/Presentation/Register/View/WindView.swift
Labels: enhancement

#17 Feat/#15
  Look-out-the-window/Look-out-the-window/Data/DTO/WeatherResponseDTO.swift
  Look-out-the-window/Look-out-the-window/Data/Model/CurrentWeather.swift
  Look-out-the-window/Look-out-the-window/Data/Network/APIEndpoints.swift
  Look-out-the-window/Look-out-the-window/Presentation/Register/View/SunriseView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/Utils/Extensions/Int+Extension.swift
Labels: enhancement

#18 Feat/#12
  Look-out-the-window/Look-out-the-window/App/AppDelegate.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/VIewController/BackgroundViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/BackgroundTopInfoView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/NotificationTest.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/RiveNames.swift
  Look-out-the-window/Look-out-the-window/Resources/Riv/Fog.riv
Labels: enhancement

#20 Feat/#1 maincollectionview
  Look-out-the-window/Look-out-the-window/Presentation/Main/MainCompositionalLayout.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/MainSectionDataModel.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/VIewController/MainViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/Cell/DailyCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/Cell/DetailCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/Cell/HourlyCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/MainHeaderView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/MainView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/ProgressBarView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/RoundedBackgroundView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/UVProgressBarView.swift
Labels: enhancement

#19 Feat/#4 CoreData 구현 및 엔티티 relationship 생성
  Look-out-the-window/Look-out-the-window.xcodeproj/project.pbxproj
  Look-out-the-window/Look-out-the-window/App/RequestAuthManager.swift
  Look-out-the-window/Look-out-the-window/Data/Model/CurrentWeather.swift
  Look-out-the-window/Look-out-the-window/Data/PersistentStorages/CoreDataStorage/CoreDataManager.swift
  Look-out-the-window/Look-out-the-window/Data/PersistentStorages/CoreDataStorage/CoreDataStorage.xcdatamodeld/CoreDataStorage.xcdatamodel/contents
  Look-out-the-window/Look-out-the-window/Presentation/Main/VIewController/MainViewController.swift
  Look-out-the-window/Look-out-the-window/Resources/Info.plist
Labels: enhancement

#21 [Feat] #5 - CoreLocation, 지역별 날씨 ListView UI 구현
  Look-out-the-window/Look-out-the-window.xcodeproj/project.pbxproj
  Look-out-the-window/Look-out-the-window/App/AppDelegate.swift
  Look-out-the-window/Look-out-the-window/App/SceneDelegate.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/.gitkeep
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/Cell/RegionCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/Cell/RegionCellBGView.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/Cell/SearchResultCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/RegionListView.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/SearchResultView.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/.gitkeep
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/Delegates/SearchResultViewControllerDelegate.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/RegionListViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/SearchResultViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewModel/.gitkeep
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewModel/RegionListViewModel.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewModel/SearchResultViewModel.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/CoreLocation/CoreLocationManager.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/CoreLocation/Model/LocationModel.swift
  Look-out-the-window/Look-out-the-window/Resources/Info.plist
Labels: enhancement

#29 fix: #27 - 데이터 모델 항목 변경
  Look-out-the-window/Look-out-the-window/Data/DTO/DailyWeatherDTO.swift
  Look-out-the-window/Look-out-the-window/Data/DTO/HourlyWeatherDTO.swift
  Look-out-the-window/Look-out-the-window/Data/DTO/WeatherResponseDTO.swift
  Look-out-the-window/Look-out-the-window/Data/Model/CurrentWeather.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/MainSectionDataModel.swift
Labels: HOTFIX

#30 Feat/#26
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/LodingIndicatorView.swift
Labels: enhancement

#33 feat: #32 -PushNotificationCenter 구현
  Look-out-the-window/Look-out-the-window/App/AppDelegate.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/NotificationTest.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/PushNotification/PushNotificationCenter.swift
Labels: enhancement

#35 Feat/#24 - Hourly Section, Daily Section 구현 완료 / Detail Section 일부 개선 필요
  Look-out-the-window/Look-out-the-window.xcodeproj/project.pbxproj
  Look-out-the-window/Look-out-the-window/Data/PersistentStorages/CoreDataStorage/CoreDataManager.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/MainCompositionalLayout.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/MainSectionDataModel.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/VIewController/BackgroundViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/VIewController/MainViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/BottomInfoView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/Cell/DailyCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/Cell/DetailCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/Cell/HourlyCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/DetailCellView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/MainHeaderView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/ProgressBarView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/RoundedBackgroundView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/UVProgressBarView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Register/View/SunriseView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Register/View/WindView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/Utils/Extensions/Double+Extensions.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/Utils/Extensions/Int+Extension.swift
Labels: enhancement

#36 Feat/#23 CoreData 시간/날씨별 콜렉션뷰에 fetch 기능 구현
  Look-out-the-window/Look-out-the-window/Data/CoreLocation/CoreLocationManager.swift
  Look-out-the-window/Look-out-the-window/Data/PersistentStorages/CoreDataStorage/CoreDataManager.swift
  Look-out-the-window/Look-out-the-window/Data/PersistentStorages/CoreDataStorage/CoreDataStorage.xcdatamodeld/CoreDataStorage.xcdatamodel/contents
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/BottomInfoView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/ViewModel/MainViewModel.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/Utils/Extensions/Int+Extension.swift
Labels: enhancement

#45 [Feat] #25 - 지역 날씨 리스트 UI
  Look-out-the-window/Look-out-the-window/Data/CoreLocation/CoreLocationManager.swift
  Look-out-the-window/Look-out-the-window/Data/DTO/WeatherResponseDTO.swift
  Look-out-the-window/Look-out-the-window/Data/Model/CurrentWeather.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/MainSectionDataModel.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/Mock/MockCurrentWeather.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/Cell/RegionWeatherCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/Cell/RoundedTrapezoidView.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/View/RegionWeatherListView.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/DataSource/RegionWeatherListSection.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/RegionWeatherListViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/SearchResultViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewModel/RegionWeatherListViewModel.swift
Labels: enhancement

#47 Feat/#40
  Look-out-the-window/Look-out-the-window.xcodeproj/project.pbxproj
  Look-out-the-window/Look-out-the-window/Data/Model/CurrentWeather.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/WeatherDetailCollectionView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Main/View/BackgroundTopInfoView.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/SearchResultViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/Register/ViewController/.gitkeep
  Look-out-the-window/Look-out-the-window/Presentation/Register/ViewController/RegisterViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/Register/ViewModel/.gitkeep
  Look-out-the-window/Look-out-the-window/Presentation/Register/ViewModel/RegisterViewModel.swift
Labels: enhancement

#60 Feat/#54
  .DS_Store
  Look-out-the-window/Look-out-the-window/Data/Model/CurrentWeather.swift
  Look-out-the-window/Look-out-the-window/Data/Model/DetailModel.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/Cell/DailyCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/Cell/DetailCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/Cell/DetailCellView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/MainCompositionalLayout.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/MainLoadingIndicator.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/ProgressBarView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/SunriseView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/WeatherDetailCollectionView.swift
  Look-out-the-window/Look-out-the-window/Presentation/RegionList/ViewController/RegionWeatherListViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/Utils/Extensions/Double+Extensions.swift
  Look-out-the-window/Look-out-the-window/Presentation/Shared/Utils/Extensions/String+Extensions.swift
  Look-out-the-window/Look-out-the-window/Presentation/WeatherDetail/View/WeatherDetailScrollView.swift
Labels: enhancement

#63 fix: #62 - Hourly Section Cell 가로 스크롤 범위 벗어나는 이슈 해결 , 레이아웃 재배치
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/Cell/DailyCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/Cell/HourlyCell.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/MainCompositionalLayout.swift
  Look-out-the-window/Look-out-the-window/Presentation/Common/View/RoundedBackgroundView.swift
  Look-out-the-window/Look-out-the-window/Presentation/Register/ViewController/RegisterViewController.swift
  Look-out-the-window/Look-out-the-window/Presentation/WeatherDetail/View/WeatherDetailScrollView.swift
Labels: bug
